# Generated by Django 3.0.6 on 2022-02-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capacitydata',
            table='capacity_data',
        ),
    ]
