# Generated by Django 3.2.8 on 2022-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeprocurementapprovaldata',
            name='request_id',
            field=models.CharField(max_length=128),
        ),
    ]
