# Generated by Django 3.2.8 on 2022-02-07 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_app', '0002_auto_20220204_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('request_id', models.CharField(max_length=128)),
                ('updated_time', models.DateTimeField()),
                ('data_center', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=64)),
                ('std_stable_1', models.FloatField()),
                ('std_stable_2', models.FloatField()),
                ('std_arbor', models.FloatField()),
                ('stable_1', models.FloatField()),
                ('stable_2', models.FloatField()),
                ('arbor', models.FloatField()),
                ('gravit', models.FloatField()),
                ('move_group_name', models.CharField(max_length=64)),
                ('remarks', models.CharField(max_length=256)),
                ('tkt_status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'history_capacity_data',
            },
        ),
        migrations.AddField(
            model_name='capacitydata',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capacitydata',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='capacitydata',
            table='request_capacity_data',
        ),
    ]
