# Generated by Django 3.2.8 on 2022-03-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_app', '0003_auto_20220330_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplannerhistorydata',
            name='request_id',
            field=models.CharField(max_length=20),
        ),
    ]
