# Generated by Django 3.2.8 on 2022-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_app', '0003_auto_20220207_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitydata',
            name='updated_time',
            field=models.CharField(max_length=128),
        ),
    ]
