# Generated by Django 3.2.8 on 2022-03-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_app', '0004_alter_projectplannerhistorydata_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplannerhistorydata',
            name='request_id',
            field=models.CharField(max_length=128),
        ),
    ]
