# Generated by Django 3.2.8 on 2022-02-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_app', '0004_alter_capacitydata_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitydata',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
