# Generated by Django 3.2.8 on 2022-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_app', '0006_projectplannerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'milestone_data',
            },
        ),
    ]
