# Generated by Django 3.2.8 on 2022-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_app', '0010_alter_financeprocurementapprovaldata_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeprocurementapprovaldata',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
